Catkin-ProjectName: darc_demo
Description:
Author: Morten Kjaergaard <mkjargaard@willowgarage.com>
Maintainer: Morten Kjaergaard <mkjargaard@willowgarage.com>
Homepage:
Vcs-Git:

Version: 0.0.1

Depends: darc, geometry_experimental

Catkin-CopyrightType: willowgarage
Catkin-DebRulesType: python_distutils
